catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("book/create/", views.BookCreate.as_view(), name="book-create"),
    path(
        "book/<int:pk>/update/", views.BookUpdate.as_view(), name="book-update"
    ),
    path(
        "book/<int:pk>/delete/", views.BookDelete.as_view(), name="book-delete"
    ),
    #
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path(
        "author/<int:pk>",
        views.AuthorDetailView.as_view(),
        name="author-detail",
    ),
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path(
        "author/<int:pk>/update/",
        views.AuthorUpdate.as_view(),
        name="author-update",
    ),
    path(
        "author/<int:pk>/delete/",
        views.AuthorDelete.as_view(),
        name="author-delete",
    ),
    #
    path(
        "mybooks/",
        views.LoanedBooksByUserListView.as_view(),
        name="my-borrowed",
    ),
    path(
        r"borrowed/",
        views.LoanedBooksAllListView.as_view(),
        name="all-borrowed",
    ),
    path(
        "book/<uuid:pk>/renew/",
        views.renew_book_librarian,
        name="renew-book-librarian",
    ),
    #
    path(
        "search/", views.SearchResultsListView.as_view(), name="search-results"
    ),
]

config/urls.py
"""URLs for the library  project."""
from django.conf import settings  # noqa:F401
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Django admin
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("resources/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Local apps
    path("accounts/", include("accounts.urls")),
    path("", include("pages.urls")),
    path("catalog/", include("catalog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
if settings.DEBUG:
    import debug_toolbar  # noqa: F401  # pragma: no cover

    urlpatterns = [  # pragma: no cover
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns
"""

pages/urls.py
from django.urls import path

from .views import (
    AboutPageView,
    ContactView,
    HomePageView,
    SuccessView,
)

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactView, name="contact"),
    path("success/", SuccessView, name="success"),
    path("", HomePageView.as_view(), name="home"),
]

catalog/models.py
import uuid
from datetime import date

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200, help_text="Enter the book's language")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    pages = models.IntegerField(null=True, blank=True, help_text="Number of Pages")
    publisher = models.CharField(max_length=40, blank=True)
    pubdate = models.DateField(null=True, blank=True, help_text="Date Published")
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book."
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text="13 Character <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>",  # noqa:E501,B950
    )
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)
    cover = models.ImageField(upload_to="covers/", blank=True)

    class Meta:
        ordering = ["title", "author"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Creates a string for Genre. Required for Admin display"""
        return ", ".join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Represents a specific copy of a book"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this book across whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL, null=True, blank=True
    )

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On Loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book Availability",
    )

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return "{0} ({1})".format(self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(
        max_length=100, blank=True, help_text="Middle Name(initial)"
    )
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def __str__(self):
        if self.middle_name is not None:
            return f"{self.last_name}, {self.first_name} {self.middle_name}"
        else:
            return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError


class RenewBookForm(forms.Form):
    """Form for a librarian to renew books."""

    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3)."
    )

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError("Invalid date - renewal in past")

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                "Invalid date - renewal more than 4 weeks ahead"
            )

        # Remember to always return the cleaned data.
        return data

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import RenewBookForm
from .models import Author, Book, BookInstance


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact="a"
    ).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
    }

    return render(request, "index.html", context=context)


class BookListView(ListView):
    """Generic class-based view for a list of books."""

    model = Book
    paginate_by = 10


class BookDetailView(DetailView):
    """Generic class-based detail view for a book."""

    model = Book


class AuthorListView(ListView):
    """Generic class-based list view for a list of authors."""

    model = Author
    paginate_by = 10


class AuthorDetailView(DetailView):
    """Generic class-based detail view for an author."""

    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact="o")
            .order_by("due_back")
        )


class LoanedBooksAllListView(PermissionRequiredMixin, ListView):
    model = BookInstance
    permission_required = "catalog.can_mark_returned"
    template_name = "catalog/bookinstance_list_borrowed_all.html"
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact="o").order_by(
            "due_back"
        )


@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == "POST":

        # Create a form instance and populate it with data
        # from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we
            # just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data["renewal_date"]
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse("all-borrowed"))

    # If this is a GET (or any other method) create the default form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(
            weeks=3
        )
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date})

    context = {
        "form": form,
        "book_instance": book_instance,
    }

    return render(request, "catalog/book_renew_librarian.html", context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_birth": "02/02/1882"}
    permission_required = "catalog.can_mark_returned"
    template_name = "catalog/author_create.html"


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = [
        "first_name",
        "last_name",
        "middle_name",
        "date_of_birth",
        "date_of_death",
    ]
    permission_required = "catalog.can_mark_returned"
    template_name = "catalog/author_update.html"


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = "catalog.can_mark_returned"
    success_url = reverse_lazy("authors")


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = [
        "title",
        "author",
        "pages",
        "publisher",
        "pubdate",
        "summary",
        "isbn",
        "genre",
        "language",
    ]
    permission_required = "catalog.can_mark_returned"
    template_name = "catalog/book_create.html"


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = [
        "title",
        "author",
        "pages",
        "publisher",
        "pubdate",
        "summary",
        "isbn",
        "genre",
        "language",
    ]
    permission_required = "catalog.can_mark_returned"
    template_name = "catalog/book_update.html"


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy("books")
    permission_required = "catalog.can_mark_returned"


class SearchResultsListView(ListView):
    model = Book
    context_object_name = "books"
    template_name = "catalog/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Book.objects.filter(
            Q(title__icontains=query)
            | Q(author__first_name__icontains=query)
            | Q(author__middle_name__icontains=query)
            | Q(author__last_name__icontains=query)
            | Q(language__name__icontains=query)
            | Q(publisher__icontains=query)
            | Q(pubdate__icontains=query)
            | Q(genre__name=query)
        ).distinct()

templates/catalog/author_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <p>
      <h2>Delete Author:</h2>
      <p>Are you sure you want to delete the author: {{ author }}?</p>
      <form action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <button class="btn btn-danger" type="submit">Yes, delete.</button>
        <a class="btn btn-info" href="{% url 'author-detail' author.id %}">Cancel</a>
      </form>
    </p>
  </div>
{% endblock content %}

templates/catalog/author_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Add New Author
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Add a new author:</h2>
      <form class="col-md-6" action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <button class="btn btn-outline-dark" type="submit">Submit</button>
        <a class="btn btn-info" href="#" onclick="window.history.back()">Cancel</a>
      </form>
    </p>
  </div>
{% endblock %}

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block title %}
  {{ author.first_name }} {{ author.last_name }}
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Author: {{ author }}</h2>
      <p>
        {{ author.date_of_birth }} -
        {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}
      </p>
      <div class="author">
        <h4>Books</h4>
        <dl>
          {% for book in author.book_set.all %}
            <dt>
              <a href="{% url 'book-detail' book.pk %}">{{ book }}</a> ({{ book.bookinstance_set.all.count }})
            </dt>
            <dd>
              {{ book.summary }}
            </dd>
          {% endfor %}
        </dl>
      </div>
      {% if user.is_staff %}
        <a class="btn btn-danger" href="{% url 'author-delete' author.id %}">Delete Author</a>
        <a class="btn btn-info" href="{% url 'author-update' author.id %}">Update Author</a>
      {% endif %}
    </p>
  </div>
{% endblock content %}

templates/catalog/author_list.html
{% extends "base.html" %}

{% block title %}
  Author List
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Author List</h2>
      {% if author_list %}
        <ul>
          {% for author in author_list %}
            <li>
              <a class="btn btn-outline-dark mb-2"
                 href="{{ author.get_absolute_url }}">
                {{ author }} ({{ author.date_of_birth }} -
                {% if author.date_of_death %}
                  {{ author.date_of_death }}
                {% else %}
                  present
                {% endif %}
                )
              </a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>There are no authors available.</p>
      {% endif %}
    </p>
  </div>
{% endblock content %}

templates/catalog/author_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Update {{ author.first_name }} {{ author.last_name }}
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Edit author details:</h2>
      <form class="col-md-6" action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <button class="btn btn-success" type="submit">Submit</button>
        <a class="btn btn-info" href="{% url 'author-detail' author.id %}">Cancel</a>
      </form>
    </p>
  </div>
{% endblock content %}

templates/catalog/book_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Delete Book:</h2>
      <p>Are you sure you want to delete this book: {{ book }}?</p>
      <form action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <button class="btn btn-danger" type="submit">Yes, delete.</button>
        <a class="btn btn-info" href="{% url 'book-detail' book.id %}">Cancel</a>
      </form>
    </p>
  </div>
{% endblock content %}

templates/catalog/book_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Add a New Book
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Add a new book:</h2>
      <form class="col-md-6" action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <button class="btn btn-success" type="submit">Submit</button>
        <a class="btn btn-info" href="{% url 'books' %}">Cancel</a>
      </form>
    </p>
  </div>
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block title %}
  {{ book.title }}
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h3>Title: {{ book.title }}</h3>
      {% if book.cover %}
        <p>
          <img class="bookcover"
               src="{{ book.cover.url }}"
               alt="{{ book.title }}"
               height=""
               width="" />
        </p>
      {% endif %}
      <ul class="no-bullets">
        <li>
          <strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
        </li>
        <li>
          <strong>Pages:</strong> {{ book.pages }}
        </li>
        <li>
          <strong>Publisher:</strong> {{ book.publisher }}
        </li>
        <li>
          <strong>Published:</strong> {{ book.pubdate }}
        </li>
        <li>
          <strong>Summary:</strong> {{ book.summary }}
        </li>
        <li>
          <strong>ISBN:</strong> {{ book.isbn }}
        </li>
        <li>
          <strong>Genre:</strong> {{ book.genre.all|join:", " }}
        </li>
        <li>
          <strong>Language:</strong> {{ book.language }}
        </li>
      </ul>
      {% if user.is_staff %}
        <a class="btn btn-danger mt-2" href="{% url 'book-delete' book.id %}">Delete Book</a>
        <a class="btn btn-info mt-2" href="{% url 'book-update' book.id %}">Update Book</a>
      {% endif %}
      <div class="author">
        <h4>Copies Available:</h4>
        {% for copy in book.bookinstance_set.all %}
          <hr>
          <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
          </p>
          {% if copy.status != 'a' %}
            <p>
              <strong>Due to be returned:</strong> {{ copy.due_back }}
            </p>
          {% endif %}
          <p>
            <strong>Imprint:</strong> {{ copy.imprint }}
          </p>
          <p class="text-muted">
            <strong>Id:</strong> {{ copy.id }}
          </p>
        {% endfor %}
      </div>
    </p>
  </div>
{% endblock content %}

templates/catalog/book_list.html
{% extends "base.html" %}

{% block title %}
  Book List
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Book List</h2>
      {% if book_list %}
        <ul>
          {% for book in book_list %}
            <li>
              <a class="btn btn-outline-dark mb-2" href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>There are no books in the library.</p>
      {% endif %}
    </p>
  </div>
{% endblock content %}

templates/catalog/book_renew_librarian.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Renew {{ book_instance.book.title }}
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Renew: {{ book_instance.book.title }}</h2>
      <p>Borrower: {{ book_instance.borrower }}</p>
      <p {% if book_instance.is_overdue %}class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

      <form class="col-md-4" action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <input class="btn btn-success" type="submit" value="Submit" />
      </form>
    </p>
  </div>
{% endblock content %}

templates/catalog/book_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Update {{ book.title }}
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Update book details:</h2>
      <form class="col-md-6" action="" method="post">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <button class="btn btn-success" type="submit">Submit</button>
        <a class="btn btn-info" href="{% url 'book-detail' book.id %}">Cancel</a>
      </form>
    </p>
  </div>
{% endblock content %}

templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base.html" %}

{% block title %}
  All Borrowed Books
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>All borrowed Books</h2>
      {% if bookinstance_list %}
        <ul>
          {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
              <a class="btn btn-outline-dark btn-sm mb-2"
                 href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> Due Date: ({{ bookinst.due_back }})
              {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %}
 
              {% if perms.catalog.can_mark_returned %}
                -
                <a class="btn btn-outline-success btn-sm mb-2"
                   href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>There are no books borrowed.</p>
      {% endif %}
    </p>
  </div>
{% endblock content %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block title %}
  My Borrowed Books
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Borrowed Books</h2>
      {% if bookinstance_list %}
        <ul>
          {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
              <a class="btn btn-outline-dark btn-sm mb-2"
                 href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> Due date: ({{ bookinst.due_back }})
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>There are no books borrowed.</p>
      {% endif %}
    </p>
  </div>
{% endblock content %}

templates/catalog/search_results.html
{% extends "base.html" %}

{% block title %}
  Search
{% endblock title %}

{% block content %}
  <div class="container">
    <p>
      <h2>Search Results</h2>
      {% for book in books %}
        <div>
          <h4>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
          </h4>
          <ul class="no-bullets">
            <li>Author: {{ book.author }}</li>
            <li>Genre: {{ book.display_genre }}</li>
            <li>Language: {{ book.language }}</li>
          </ul>
        </div>
      {% endfor %}
    </p>
  </div>
{% endblock content %}